# Generated by Django 4.1.4 on 2022-12-13 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('speedapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Current', 'Current'), ('Savings', 'Savings')], max_length=100, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.FloatField(default=100000.0, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='account',
            name='bank',
            field=models.CharField(choices=[('First Bank', 'First Bank'), ('Zenith', 'Zenith'), ('Gt Bank', 'Gt Bank')], max_length=100, verbose_name='Bank'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedapp.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='speedapp.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='withdraw',
            name='amount',
            field=models.FloatField(verbose_name='Amount'),
        ),
    ]
