# Generated by Django 4.1.4 on 2022-12-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('speedapp', '0002_alter_account_account_type_alter_account_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='withdraw',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
